### ISSUE TITLE
`os.path.join` is not suitable for navigating in hdf5 tree on windows 

### ISSUE THREAD

**Issue by Animadversio** [anvoynov/BigGANsAreWatching#1]
Hi, I really like your BIgBiGAN2BigGAN code and it's super useful! 
However running the code on Windows system will generate the error below, and after quick debugging, I find it's the path format is unrecognizable to hdf5. 
'''
KeyError: "Unable to open object (object 'module\\Generator\\GBlock\\conv0\\u0:0' doesn't exist)"'
'''
And after using `/` as separator instead of `\\` everything works like charm! 
So I suggest a quick and dirty solution to enhance compatibility is to add `.replace("\\", "/")` to L149, L175, L189 in `tf_to_torch`

**Comment by anvoynov** [comment]
Hi @Animadversio, thank you for the report!
This tf_to_torch.py is basically based on https://github.com/ajbrock/BigGAN-PyTorch/blob/master/TFHub/converter.py with a few modifications. The problem seems to appear due to os.path.join()'s different behavior on Windows and Linux. Apparently, it would be more convenient to replace it with an f-string.
